---
namespace: solr-zookeeper

stack:
  defines: process-group
  metadata:
    name: solr-zookeeper
    shortname: solr-zookeeper
    description: |
      Apache Solr is a popular, open-source enterprise search platform that provides fast and scalable full-text search capabilities.
      Built on top of the Apache Lucene search library, Solr offers a wide range of features and functionalities for indexing, searching, and analyzing large volumes of data.
      It is highly scalable, with support for distributed search and indexing, and can be used in a variety of applications, including e-commerce, content management systems (CMS), and big data analytics.
      Solr provides advanced search features such as faceted search, which allows users to refine search results based on specific criteria, and text analysis, which can help identify relevant information from unstructured data.
      It also offers support for document management, enabling users to search and retrieve content from a wide range of file formats.
      Overall, Solr is a powerful and flexible search platform that can be used to build fast and effective search solutions for enterprise-level applications.
    tags: Search engine, Full-text search, Indexing, Apache Lucene, Open source, Scalability, High performance, Faceted search, Apache Software Foundation, Text analysis, Document management, E-commerce, Content management systems (CMS), Big data, Enterprise search
    website: https://solr.apache.org/
    source: https://github.com/apache/solr
    publisher: monk.io
    icon: https://norconex.com/wp-content/uploads/Solr_Logo_on_white_web.png
    private: false
  runnable-list:
    - solr-zookeeper/solr-1
    - solr-zookeeper/solr-2
    - solr-zookeeper/solr-3
    - solr-zookeeper/zookeeper-1
  variables:
    solr-image-tag:
      type: string
      value: latest
    zookeeper-image-tag:
      type: string
      value: 3.8.0
